### PR TITLE
Add 'html-live' make action to support live reload workflows

### PR DESCRIPTION
**Pull request by jaimergp**
# Description

This PR adds a `html-live` make action so we can write docs locally without having to rebuild and serve manually. This depends on `sphinx-autobuild`.

This is all you need:

```bash
$ cd docs/
$ make html-live
```

The incremental builds are still a bit slow, so it's not exactly "live" but, it's indeed automated :) I've been using this in the background while live previewing the markdown files on VS Code directly. Then, I switch to the browser to double check.

## Type of change

- [ ] Fixes or improves existing content
- [ ] Adds new content page(s)
- [X] Fixes or improves workflow, documentation build or deployment

# References

## Final checklist:
- [X] My PR is the minimum possible work for the desired functionality
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Review by melissawm — APPROVED** [review]
Thanks, @jaimergp - will leave it to maintainers but looks good to me :)

**Comment by psobolewskiPhD** [comment]
@jaimergp 
I think the command should be `make html-live`? I can't get the one in the OP working.
BTW For anyone testing this, the docs get served at http://127.0.0.1:8000

Also, does the requirements.txt in the root need to be updated?
Edit: `make docs-install` doesn't install from the nested requirements.txt, so yea, i think the main one also needs updating.


BTW, is this intended to just chain build regardless of whether I do anything?
I kind of expected it to only build when I change/edit something. Am I missing something?

**Comment by jaimergp** [comment]
It shouldn't loop. I have tested this from `docs/` itself, not from the root... maybe that's the issue?

(Updated OP just in case).

**Comment by psobolewskiPhD** [comment]
When I `cd docs` and try `make html-live`, I get:
```
make: *** No rule to make target `html-live'.  Stop.
```

**Comment by melissawm** [comment]
The Makefile is at the root so running it from inside the docs folder won't work. And yes, in that case sphinx-autobuild also needs to be added to the root requirements. I honestly never use the requirements.txt from inside the docs folder, would gladly just merge it into one file at the root folder and make it simpler - I think this should be possible after #41 is merged

**Comment by jaimergp** [comment]
Thank you both, looking into the issues!

**Comment by jaimergp** [comment]
I caught up with the discussion at #41 so I'll probably wait a bit before I continue iterating here. @melissawm, let me know if you need any help!

**Comment by psobolewskiPhD** [comment]
#41 is merged

**Comment by psobolewskiPhD** [comment]
So the install and everything works now, but I'm still not clear if `make html-live` should result in the terminal chain running. 
The first time it pops all the napari windows, but after that it's still "working" so to speak, churning away through percents of the gallery, embedding hyperlinks, etc. Perhaps this is what it's supposed to do? 🤷‍♂️

**Comment by jaimergp** [comment]
At some point it should stop and wait for your changes. Everything else should be cached :(

Can you book a slot on [my calendar here](https://calendly.com/jaimergp-quansight/30-min-call?month=2023-02) so we can debug a bit? 🙏

**Comment by psobolewskiPhD** [comment]
Let me try one more time with a totally fresh and clean env later today and then we'll see whats up.

**Comment by psobolewskiPhD** [comment]
The setup:
Fresh conda-forge 3.9 env with pyqt (i'm on arm64 macOS)
`pip install -e .[dev]` in my napari repo (main)
switch to docs repo, checkout this branch.
`python -m pip install -r requirements.txt`
`make html-live`


What seems to be happening is each time it builds, it finds a change in a notebook:
e.g.
```
embedding documentation hyperlinks for gallery... [100%] magic_image_arithmetic.html
[sphinx-autobuild] Serving on http://127.0.0.1:8000
[I 230207 19:42:29 watcher:110] Running task: build (delay: None)
[sphinx-autobuild] Detected change: /Users/piotrsobolewski/Dev/napari-docs/docs/gallery/magic_image_arithmetic.ipynb
```
or a `.pickle`:
```
embedding documentation hyperlinks for gallery... [100%] magic_image_arithmetic.html
[sphinx-autobuild] Serving on http://127.0.0.1:8000
[I 230207 19:43:58 watcher:110] Running task: build (delay: None)
[sphinx-autobuild] Detected change: /Users/piotrsobolewski/Dev/napari-docs/docs/gallery/custom_key_bindings_codeobj.pickle
[sphinx-autobuild] > sphinx-build -b html -D plot_gallery=0 -D sphinx_gallery_conf.examples_dirs=../../napari/examples /Users/piotrsobolewski/Dev/napari-docs/docs /Users/piotrsobolewski/Dev/napari-docs/docs/_build
```
I'll let it run a bit longer, maybe eventually it does finish...

Edit: It's done that same `.pickle` 5 times in a row now, so I think something isn't quite right.

**Comment by jaimergp** [comment]
Yea it's picking changes in `gallery`. Technically that directory is ignored, but maybe something was off. I changed how it finds it, so maybe it now works? Otherwise, the problematic lines should be [these ones](https://github.com/jaimergp/napari-docs/blob/32ad0c51c294f5e863d7248b9bb3a3922c9213fb/Makefile#L46-L49).

**Comment by psobolewskiPhD** [comment]
OK!! NOW WE'RE TALKING!!
Now it runs through once, with all the napari opening closing and finishes with:
```
[I 230208 14:19:10 server:335] Serving on http://127.0.0.1:8000
[I 230208 14:19:10 handlers:62] Start watching changes
[I 230208 14:19:10 handlers:64] Start detecting changes
```
I then was able to load the preview from that link into browser. Sweet 👍 
I used VS Code to edit a file.
```
[I 230208 14:19:20 handlers:135] Browser Connected: http://127.0.0.1:8000/
[I 230208 14:19:50 watcher:110] Running task: build (delay: None)
[sphinx-autobuild] Detected change: /Users/piotrsobolewski/Dev/napari-docs/docs/index.md
[sphinx-autobuild] > sphinx-build -b html -D plot_gallery=0 -D sphinx_gallery_conf.examples_dirs=../../napari/examples /Users/piotrsobolewski/Dev/napari-docs/docs /Users/piotrsobolewski/Dev/napari-docs/docs/_build
```
This still took a bit of time, but didn't do all the napari open closes, so it's still much faster, just not live, like you mentioned.
That finished with 
```
[sphinx-autobuild] Serving on http://127.0.0.1:8000
[I 230208 14:20:20 handlers:92] Reload 1 waiters: /Users/piotrsobolewski/Dev/napari-docs/docs/index.md
[I 230208 14:20:20 handlers:135] Browser Connected: http://127.0.0.1:8000/
```
And my window was reloaded with the changes.

This is pretty darn sweet!
I think maybe a line of documentation in the 3. Preview section main? would be nice, otherwise good to go.
https://github.com/napari/docs/blob/main/docs/developers/documentation/index.md
There's an issue regarding docs building docs: https://github.com/napari/docs/issues/19 so I'm not sure something elaborate is needed, but something to document the existence of the feature outside this PR is important though.

Edit: one more thing: how do you stop it? I did control-c, which worked:
`^C[I 230208 14:28:59 server:358] Shutting down...`
But good to mention that probably in the docs too.

**Review by psobolewskiPhD — CHANGES_REQUESTED** [review]
As mentioned in my post, for me this works **really** nice now.
The docs are also fully build, as far as I can tell, so there is no real drawback of this. 
As such, I think it needs a line in the contributing docs documentation in the 3. Preview... so people can use this! (also with info how to stop it—control-c ?)

**Comment by melissawm** [comment]
We could do the instructions in a follow-up to not make this PR linger - but I am also definitely +1 on this, thanks @jaimergp !

**Comment by jaimergp** [comment]
This works reasonably well now, although it's still a PITA that all the outputs are regenerated in every run! It's like something it's injecting the `-a` (all files` `sphinx-build` flag, but I couldn't find it. We would have to comb through all the extensions and find the culprit, but that's a journey for another day.

Let me know what you think of the docs! I added a couple headers for navigation.

And thanks for review and kind words! <3

**Comment by psobolewskiPhD** [comment]
How about stopping/canceling? Is Control-C the way to go?

**Comment by jaimergp** [comment]
Oopsie, forgot about that. I'll add it. Yes, it's the way.

**Comment by jaimergp** [comment]
Reworded a bit, fixed a typo (I was insisting again with `live-html`), and added parallelism.

**Review by psobolewskiPhD — APPROVED** [review]
Ok, this is working great and the Note looks awesome—I used the html-live to preview it! 🎉

**Comment by psobolewskiPhD** [comment]
I've posted in zulip to see if anyone else has any comments. 
I'd like to merge in 24 hrs if no-one has any objections.

**Review by Czaki — APPROVED** [review]
looks good

**Pull request merged**
