### PR TITLE
DOC Add section on order of app-model init steps 

### PR DESCRIPTION
**Pull request by lucyleeow**
# References and relevant issues
Related: https://github.com/napari/napari/issues/6778

# Description
Add section on when things occur during app-model setup.

### CODE REVIEW

**Comment by lucyleeow** [comment]
cc @DragaDoncila

**Review by DragaDoncila — APPROVED** [review]
Yep, lgtm thanks Lucy, it's good to actually have this somewhere

**Comment by melissawm** [comment]
I just noticed that some of the objects you are trying to link to are not exposed to the docs @lucyleeow - for example `napari.plugins._initialize_plugins` and `napari._app_model.get_app` - I am assuming the latter is not `napari.qt.get_app`?

Is it ok if I convert those to regular tt font and remove the attempt to linking with `{func}` before merging? Thanks!

**Comment by lucyleeow** [comment]
Ah yes of course. Forgot they are private. Thanks!

**Comment by lucyleeow** [comment]
I've removed all links to private objects now!

**Comment by DragaDoncila** [comment]
Awesome, will merge now! Thanks @lucyleeow

**Pull request merged**
