### PR TITLE
Add pr dependency check

### PR DESCRIPTION
**Pull request by brisvag**
# Description
Followup on [these comments](https://github.com/napari/docs/pull/123#issuecomment-1476477928), adding a dependency check for PRs.

This will automatically detect stuff like:
- depends on #123
- blocked by https://github.com/napari/napari/issues/5650

and it also works cross-repo (which is especially useful here to ensure we merge docs only if the feature actually landed in napari core).

## Type of change

- [ ] Fixes or improves existing content
- [ ] Adds new content page(s)
- [x] Fixes or improves workflow, documentation build or deployment

# References

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Comment by brisvag** [comment]
I created https://github.com/napari/napari/issues/5650 to test the functionalilty, and it's correctly being marked as failed since that issue is still open. We should now be able to close that issue and I guess we have to rerun the ci job to recheck?

**Review by psobolewskiPhD — APPROVED** [review]
I love this; the yml looks right (just like the example) and it seems like it works!
Thanks @brisvag

**Review by Czaki — APPROVED** [review]

**Comment by brisvag** [comment]
It's a pity the check doesn't get somehow automatically updated to `pass` when the dependency is closed, but oh well :P

**Comment by psobolewskiPhD** [comment]
> It's a pity the check doesn't get somehow automatically updated to `pass` when the dependency is closed, but oh well :P

You manually re-ran CI?

**Comment by Czaki** [comment]
> It's a pity the check doesn't get somehow automatically updated to `pass` when the dependency is closed, but oh well :P

It looks impossible with the current GitHub event system.

**Comment by brisvag** [comment]
> You manually re-ran CI?

yes, I clicked on 'rerun failed jobs'.

**Comment by psobolewskiPhD** [comment]
This has approvals and I think it's useful, flagging to get merged.

**Pull request merged**
