### PR TITLE
Fix rendering explanation broken links

### PR DESCRIPTION
**Pull request by melissawm**
# References and relevant issues
Addresses part of #436 

# Description
Fixes a few broken links in the rendering guide.

Also changes an old link to the rendering-explanation guide to a hard-link since this document has been removed.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
~~Huh, what happened to the circleCI run?~~
Nvm, I guess I needed to reload.

**Review by psobolewskiPhD — APPROVED** [review]
Thanks for catching these!!
❤️

**Review by andy-sweet — APPROVED** [review]
Thanks for catching and fixing these!

**Comment by melissawm** [comment]
Self-merging with two approvals, and to test the new unversioned pages deployment 🎉

**Pull request merged**
