### PR TITLE
Fix docs CI

### PR DESCRIPTION
**Pull request by melissawm**
# References and relevant issues
N/a

# Description
Pins sphinx<8 to prevent deprecation warnings, and fixes a few broken references.

### CODE REVIEW

**Comment by melissawm** [comment]
I will submit a PR to napari/napari to update the constraints there.

**Comment by Czaki** [comment]
> I will submit a PR to napari/napari to update the constraints there.

We may merge this, and the trigger rebuild constraints in napari.

**Comment by melissawm** [comment]
Your call 😄 thanks!

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
I have added a comment to trigger ci.

**Pull request merged**
