### PR TITLE
Use tabs for the install as Python package guide

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# References and relevant issues
This came up at the docs workgroup and also:
https://github.com/napari/docs/pull/274#pullrequestreview-1740859412

# Description
Currently, the install docs have pip, conda and GitHub install instructions in series followed by the `checking that it worked`. No-one will use all three approaches.
In this PR instead Tabs are used for *each* of the approaches, to let the user choose an install strategy. 
This makes the install page simpler and cleaner, leading the user to the the next logical step.

What it looks like:
image

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Here's the new section in the CircleCI docs preview:
https://output.circle-artifacts.com/output/job/5bd089ca-8cda-48fa-a4af-d9cf370c1e0a/artifacts/0/docs/docs/_build/tutorials/fundamentals/installation.html#install-as-python-package-recommended

**Review by jni — APPROVED** [review]
Love this! 😍

btw we can/should probably add "conda nightlies" as an option. Might get me using them more. 😂 But that can come in a subsequent PR.

**Comment by psobolewskiPhD** [comment]
I was thinking about that. 
Not even sure i like the `from main` on the same level as the regular install options, but if we are to keep it there, then adding conda nightlies to that tab makes sense.

**Review by melissawm — APPROVED** [review]
Love it!

**Comment by jni** [comment]
I've raised #315 to discuss the nightlies issue in a dedicated space. 😊

**Pull request merged**
