### PR TITLE
Documentation for alt-click visibility icon to show only that layer (napari/napari#5618)

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description

This PR adds documentation for https://github.com/napari/napari/pull/5618
a PR that enables alt-click on the visibility button (eye icon) to show just that layer, while hiding others.
This new feature is now mentioned in the Viewer tutorial and Layers-at-a-glace guide.

## Type of change

- [x] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References

Depends on https://github.com/napari/napari/pull/5618

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Review by DragaDoncila — APPROVED** [review]
Looks great, thanks for following up @psobolewskiPhD

**Review by melissawm — APPROVED** [review]

**Review by jni — APPROVED** [review]
Thanks @psobolewskiPhD! So exciting to have this in. 😃 

Note: I've changed the title to make it clearer what the PR does when looking at a `git log --pretty=oneline`, which I do a lot; I've also changed the format of the reference so that it auto-links to the correct PR.

**Comment by psobolewskiPhD** [comment]
Wonder why the dependency action isn't working properly:
https://github.com/napari/docs/actions/runs/5036977021/jobs/9033519160?pr=121#step:2:22

Edit: figured it out. I had `depends on:` with the `:`. Apparently can't have that, must be exactly `depends on` or `blocked by`

**Comment by melissawm** [comment]
But this is not blocking, right? Is this ready to merge?

**Comment by psobolewskiPhD** [comment]
@melissawm Until the actual feature is merged then I think it's best to not merge the docs:
`PR Dependency Check / Check Dependencies (pull_request) Failing`

But in terms of content, I think it's complete and correct.

**Comment by melissawm** [comment]
Got it - thanks!

**Comment by GenevieveBuckley** [comment]
Now that https://github.com/napari/napari/pull/5618 has been merged, this one can go in. Thank you @psobolewskiPhD

**Comment by psobolewskiPhD** [comment]
Note that the feature has 0.5.0 milestone:
https://github.com/napari/napari/pull/5618
so setting that here too, otherwise could lead to confusion once 0.4.18 is released.

**Pull request merged**
