### PR TITLE
Add Kyle to steering council, make Talley emeritus

### PR DESCRIPTION
**Pull request by tlambert03**
@napari/core-devs, I've always felt that the core-devs list should accurately reflect the _currently active_ team, and I don't see my activity on napari returning any time soon, so this PR moves me from "current" to "emeritus" core developers.

(It also adds a steering council asterisk for @kephale)

### CODE REVIEW

**Review by psobolewskiPhD — APPROVED** [review]
❤️

**Review by jni — APPROVED** [review]

**Comment by GenevieveBuckley** [comment]
I'm guessing you might also want to take your name off as co-leader of the plugin working group? https://napari.org/0.4.15/community/working_groups.html#existing-working-groups

**Comment by jni** [comment]
@GenevieveBuckley those changes are already in the PR ;)

**Comment by GenevieveBuckley** [comment]
argh, sorry!

**Pull request merged**
