### PR TITLE
Update NAP-6 to remove mention of context menu

### PR DESCRIPTION
**Pull request by jni**
# References and relevant issues

https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/issues/45#issuecomment-2473788143

While working on a PR with a plugin developer to update their plugin to use
NAP-6, it became clear that starting with the non-contributable layer context
menu at the very top of the NAP is very user-unfriendly. 😅

# Description

In this PR, I remove mentions of the layer context menu and instead replace the
first example in the NAP with one that works.

### CODE REVIEW

**Comment by jni** [comment]
CC @DragaDoncila

**Comment by jni** [comment]
Sorry, I've been away for a bit — can someone explain what happened to our labeler? 😅

**Review by DragaDoncila — APPROVED** [review]
Thanks for fixing this @jni! Greatly appreciated :pray:

**Comment by melissawm** [comment]
Labeler works again, thanks @psobolewskiPhD !

**Pull request merged**
