### PR TITLE
Fix CircleCI token name and remove outdated artifact action

### LINKED ISSUE #135: CircleCI redirector/docs preview not working
## 🧰 Task

Hi folks, our documentation preview link is not working due to an upstream bug.

Context: https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40#issuecomment-1505543564

Here's what needs to be done (by an org owner):

> The token must be a personal API token, not a project token at the CircleCI end as those aren't supported yet.
>
> 1. You can create a personal CircleCI token here (I named mine CIRCLE_STATUS): [app.circleci.com/settings/user/tokens](https://app.circleci.com/settings/user/tokens)
> 2. Add the token value (from the CircleCI website) it to the secrets of your org or project, e.g., for MNE-Python I added it under the name CIRCLE_TOKEN for the org to [github.com/organizations/mne-tools/settings/secrets/actions](https://github.com/organizations/mne-tools/settings/secrets/actions)
> 3. ~~Add it to the action as api-token: ${{ secrets.CIRCLECI_TOKEN }} in the with for the action~~ DONE in #136

### PR DESCRIPTION
**Pull request by melissawm**
# Description

An upstream bug has caused our docs preview link to stop working (see https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40#issuecomment-1505543564 for context)

## Type of change

- [ ] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References
See also #135

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Comment by Czaki** [comment]
Did someone need to update secrets here?

**Comment by melissawm** [comment]
Yes. What is needed is (quoting https://github.com/larsoner/circleci-artifacts-redirector-action/issues/40):

> 1. You can create a personal CircleCI token here (I named mine CIRCLE_STATUS): [app.circleci.com/settings/user/tokens](https://app.circleci.com/settings/user/tokens)
> 2. Add the token value (from the CircleCI website) it to the secrets of your org or project, e.g., for MNE-Python I added it under the name CIRCLECI_TOKEN for the org to [github.com/organizations/mne-tools/settings/secrets/actions](https://github.com/organizations/mne-tools/settings/secrets/actions)
> 3. Add it to the action as api-token: ${{ secrets.CIRCLECI_TOKEN }} in the with for the action

This PR does number 3. Numbers 1 and 2 are still necessary and need to be done by someone with the right access privileges on this repo (and also on napari/napari if we want the action to work there, too after merging napari/napari#5714)

**Comment by jni** [comment]
Ok I've added the token to the org settings (as suggested by the quoted text) rather than the settings for each repo. I think it should work anyway right @melissawm?

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
@melissawm why is the artifacts workflow removed? Just because we now rely on circleci builds pretty much?

**Comment by melissawm** [comment]
Yes - the artifact I am removing here is just the one that would comment with the link to the docs artifacts on pull requests. We are not using it now, and I think with CircleCI that should not be necessary anymore.

**Comment by melissawm** [comment]
This should be good to go then - for it to definitely work it needs to be merged to main, so I'll keep an eye out for when it is merged and make sure to follow up if there are any issues. Thanks!

**Comment by Czaki** [comment]
@melissawm I do not understand. I do not see now nice way to go to the preview documentation. Or circleCi will post it itself?

**Comment by melissawm** [comment]
This will be a link in the checks of the PR, it has been active like that for a couple of months in this repo. But the fix (this PR) needs to be merged to show it right now because of this token problem.

**Pull request merged**
