### PR TITLE
Move napari workshop template link to top of page

### LINKED ISSUE #88: Move link to the napari-workshop-template to the top of the page
## 📚 New content request

In https://napari.org/dev/further-resources/napari-workshops.html (discussed on the Docs working group meeting)

### PR DESCRIPTION
**Pull request by melissawm**
# Description
Moves information about the napari workshop template (and how to include workshops to the list) to the top of the Workshops page.

## Type of change

- [x] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References
Closes #88 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
I'm of two minds about this.
An end-user would rather get to the materials, up-front. After all, this is the Usage menu.
A contributor/organizer doesn't care and wants to get to the instructions—this would even fit in Community>Contributing. In fact, maybe we should put this on a page there and link from Usage>Workshops?

BTW, what about someone wanting to announce an up-coming napari workshop/event?

**Comment by melissawm** [comment]
I am not sure as we didn't discuss this case. Maybe @jni @DragaDoncila @chili-chiu have opinions?

**Comment by DragaDoncila** [comment]
Hmm I guess I feel like it's not really a big enough section for a user to be "confused" about where to go? Yes a usage focused visitor might not care about the template/adding a workshop to the list, but it's also pretty easy for them to skim past this. And I also feel like it's too short to warrant its own page.

@psobolewskiPhD what if we keep the template & add your own text at the top, but we encase it in a little note or info admonition, to make sure it's even easier to skim past, and takes up less room so the list of workshops is more likely to be above the fold?

**Comment by melissawm** [comment]
Here's a first try:

Screenshot_20230119_115642

**Comment by psobolewskiPhD** [comment]
I like the note idea 🤷‍♂️

**Comment by melissawm** [comment]
Ok, I'm pushing this up but if you prefer another kind of admonition we can also do that. Thanks for the feedback!

**Comment by DragaDoncila** [comment]
I like the admonition! Is it possible to make it one with a custom title so instead of Note it says "Got a workshop?" or something similar to grab people's attention.

**Comment by melissawm** [comment]
Here you go:

Screenshot_20230120_144235

**Review by DragaDoncila — APPROVED** [review]
Awesome, thanks @melissawm!

**Pull request merged**
