### PR TITLE
Add resources page with logos

### LINKED ISSUE #189: Add resources section
## 📚 New content request

Having a resources section with things like the napari logo in various formats will be nice. 

In the future, it may contain various, other resources like cheatsheet, sample presentations, etc.

### PR DESCRIPTION
**Pull request by melissawm**
# References and relevant issues
Closes #189

# Description
Adds a page under community to highlight some resources. Right now only versions of the napari logo are listed, but in the future we could include links to presentations or other resources.

### CODE REVIEW

**Review by TimMonko — APPROVED** [review]
Looks good to me. Something I've searched for many times -- glad this is being added. Maybe not the most obvious spot (I have no other suggestion), but it is easily searchable.

**Review by psobolewskiPhD — APPROVED** [review]
I dig it!
Maybe in a followup we can give theme colors?

**Comment by melissawm** [comment]
@psobolewskiPhD maybe the theme colors should be specified in the theme docs - maybe what's missing is a link to the theme pages?

**Comment by psobolewskiPhD** [comment]
Sure! 
I was also kinda thinking of the napari default themes, Dark and Light. Maybe that's silly tho?

**Pull request merged**
