### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by melissawm**
# Description

Fixes a number of broken links ~and adds a link check step to CI.~

There are a few broken links still (see https://github.com/napari/docs/pull/59#issuecomment-1407044657) but these can be fixed in a follow up. Pending is also a link check step to CI. 

## Type of change

- [x] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References
Addresses napari/docs#439

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

### CODE REVIEW

**Comment by melissawm** [comment]
I am not sure this is the best way to go, to be honest. I think a periodic check (like we had with lychee, some time ago) is the best approach - the linkcheck step in CI takes ~10 mins to run, in what is already a long CI run for the documentaion build. Let me know if you have better ideas!

**Comment by Czaki** [comment]
> . I think a periodic check

Do you mean one scheduled, for example, weekly? 

For Me best option is to run whole documentation check periodically and (I'm not sure if easy) run the check only for changed files in PR.

**Comment by melissawm** [comment]
Ok folks - to make this easier, I removed the linkcheck from CI for now, so this PR can be merged without affecting any of the workflows. I will do that in a separate PR. This one just fixes all broken links detected by linkcheck.

**Comment by Czaki** [comment]
> Ok folks - to make this easier, I removed the linkcheck from CI for now, so this PR can be merged without affecting any of the workflows. I will do that in a separate PR. This one just fixes all broken links detected by linkcheck.

Do the links not become outdated in the meantime? 
If they are ok I will merge it soon.

**Review by psobolewskiPhD — APPROVED** [review]
I've checked all the new links—not the old ones—and they all work.
So let's get this merged!
I think a link checker would be nice, maybe it could run after we merge something? like the comprehensive tests on napari/napari.

**Comment by melissawm** [comment]
There are a couple of broken links still:
- `(plugins/contributions: line  217) broken    https://napari.org/magicgui/api/_autosummary/magicgui.widgets._bases.Widget.html - 404 Client Error: Not Found for url: https://napari.org/magicgui/api/_autosummary/magicgui.widgets._bases.Widget.html` -> ~I will open a PR to npe2 to fix it there~ Fixed by https://github.com/napari/npe2/pull/270
- `(developers/testing: line   18) broken    https://www.softwaretestinghelp.com/the-difference-between-unit-integration-and-functional-testing/ - 403 Client Error: Forbidden for url: https://www.softwaretestinghelp.com/the-difference-between-unit-integration-and-functional-testing/` -> pasting the link on a browser you can access it, but maybe it has some protection against the automated linkcheck?
- `(naps/6-contributable-menus: line  397) broken    https://github.com/napari/napari/pull/5153/files/e55ed333866384d85a780b8c2ab1591fab460300#user-content-diff-4ab84b59ab3d5cadbcf97fb21bd6547982d5b444251fd627a0b50deb51bec83b - Anchor “user-content-diff-4ab84b59ab3d5cadbcf97fb21bd6547982d5b444251fd627a0b50deb51bec83b” not found` -> my guess is this should have been a permalink, but now I don't know what it should be pointing to. Maybe the NAP authors can help me here
- `(tutorials/fundamentals/quick_start: line   54) broken    https://github.com/napari/napari/releases/download/v0.4.15/napari-0.4.15-Linux-x86_64.zip - 404 Client Error: Not Found for url: https://github.com/napari/napari/releases/download/v0.4.15/napari-0.4.15-Linux-x86_64.zip` -> This is a more complicated one. Because of the current result of `napari --version` (which is still `napari version 0.4.15rc2.dev626+gca97562d`) this is pointing to the 0.4.15 release assets. The problem is that this version for some reason doesn't have a `napari-0.4.15-Linux-x86_64.zip` asset, only a `.sh`. Not sure what to do here.

**Comment by Czaki** [comment]
> I've checked all the new links—not the old ones—and they all work.

Hurray :)

**Review by Czaki — APPROVED** [review]

**Comment by Czaki** [comment]
> I think a link checker would be nice, maybe it could run after we merge something

it is a target solution, but it requires fixing all existing links. Otherwise, test will be all-time failing

**Comment by psobolewskiPhD** [comment]
@melissawm Do you want to update the name and description of the PR so it better reflects the current state? Then I think we can merge.

**Comment by melissawm** [comment]
Done!

**Pull request merged**
