### PR TITLE
Update CI actions versions

### PR DESCRIPTION
**Pull request by melissawm**
# Description
Also adds note about keeping CI files in sync across repos.

## Type of change

- [ ] Fixes or improves existing content
- [ ] Adds new content page(s)
- [x] Fixes or improves workflow, documentation build or deployment

# References
--

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Review by psobolewskiPhD — APPROVED** [review]
Thanks @melissawm !
❤️

**Comment by psobolewskiPhD** [comment]
@melissawm Do you want to update this one for the constraints from https://github.com/napari/napari/pull/5988
Or get this in as is and then make a new PR once the napari one is merged.

**Comment by melissawm** [comment]
Let me update this one, thanks for the ping!

**Comment by melissawm** [comment]
Done - also made sure to update `deploy_docs.yml` to be in sync with `build_docs.yml`

**Comment by melissawm** [comment]
The Build PR action here will fail until https://github.com/napari/napari/pull/5988 is merged.

**Comment by melissawm** [comment]
Should be good to go now!

**Pull request merged**
