### PR TITLE
CSS Carousel for the homepage

### PR DESCRIPTION
**Pull request by melissawm**
# References and relevant issues
--

# Description
Implements a basic CSS carousel for the home page.

This shows napari images, but in the future can be used for logos or any other information we want to display dynamically.

### CODE REVIEW

**Comment by jni** [comment]
In DM discussion with Melissa, we came across this site:

https://webflow.com/blog/carousel-slider-design-best-practices

Regardless of all the times it calls me out for wanting a carousel in the first place 😂 I like examples 2 (Card style slider) and 3 (Ecommerce product slider) with both dot and arrow navigation for the funders logos. I agree very much with the "don't autoplay" recommendation.

**Comment by psobolewskiPhD** [comment]
😬 
I hate carousels.
😬 
But I'll defer here to @jni this is his baby, with all that entails.

**Comment by jni** [comment]
@psobolewskiPhD then the page linked above is for you! 😂 Ok so I'm trying to figure out how to display an arbitrary number of sponsors on our home page without crowding — do you have alternative suggestions for doing that? Or maybe we reserve the home page for say 4 "Platinum" sponsors laid out horizontally, and that's it?

**Comment by psobolewskiPhD** [comment]
I think I must have missed some messages...

**Comment by jni** [comment]
It was briefly discussed in the core-dev Zulip [here](https://napari.zulipchat.com/#narrow/stream/320379-core-devs/topic/outside.20institutional.20contributions/near/435298308) (visible only to core devs).

> Here are all the things we've entertained: [for raising funding]
> - straight-up sponsorship/advertising: you give us money, you get an acknowledgement on the About page. Give us more money, get it on the home page (this isn't live yet but could be very soon thanks to Melissa's unversioned home page :partying_face: — @melissawm that reminds me, another semi-urgent docs task, a carousel for the front page!)
> - ...

**Comment by melissawm** [comment]
A few examples from other projects that may be relevant:
Screenshot_20240502_095536

Screenshot_20240502_095612
Screenshot_20240502_095718
Screenshot_20240502_095824
Screenshot_20240502_100111

Screenshot_20240502_100200

**Comment by jni** [comment]
blows my mind that pandas is still a subdomain of pydata.org. 😂 

Also blows my mind how much material theme insiders earns. 🤯

**Comment by melissawm** [comment]
Moving to draft so we can discuss more, thanks!

**Comment by melissawm** [comment]
Let's close for now, we can revisit later.

**Pull request closed without merging**
