### PR TITLE
Add matplotlib image scraper for gallery

### LINKED ISSUE #129: Feature request: Add "matplotlib" image scraper for gallery
## 🧰 Task
I'm working on a new gallery example for https://github.com/napari/napari/pull/5642, and it was suggested to add some images using `plt.imshow`. I tried this, but it didn't immediately work. Eventually I found that sphinx-gallery has configurable [image scrapers](https://sphinx-gallery.github.io/stable/configuration.html#image-scrapers). They offer a matplotlib scraper, and in fact it is on by default, but we change the configuration to use a qt scraper (overriding the default): https://github.com/napari/docs/blob/7f74c93a6b6040d6b19a35577419d981f069b33e/docs/conf.py#L223

Testing locally shows just adding `"matplotlib"` there works as I would expect. I just wanted to check if this was intentionally removed for some reason before I open a PR.

### PR DESCRIPTION
**Pull request by aganders3**
# Description
As described in #129, adding this scraper allows the use of matplotlib to create plots, etc. in gallery examples.

## Type of change
- [x] Fixes or improves workflow, documentation build or deployment

# References
closes #129 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Review by melissawm — APPROVED** [review]
Looks good to me, thanks @aganders3 ! It's also a good reminder that we don't have a guide for writing new examples for the gallery, ~~I'll open an issue about it.~~ Nevermind, I'd already opened it at #92

**Comment by aganders3** [comment]
Cool - now that I've done it I might be able to help with that guide 😆

**Review by jni — COMMENTED** [review]
Thanks for the improvement! I'm just vaguely curious — why is one config item a string while the other is an actual function/module? It's hurting my OCD. 😜

**Review by jni — APPROVED** [review]

**Comment by aganders3** [comment]
It's because the matplotlib scraper comes with the package (sphinx-gallery) so is more like a config option here. Maybe there's a way to import the function instead to satisfy your OCD. 😆

**Comment by jni** [comment]
Reading [the image scrapers page](https://sphinx-gallery.github.io/stable/configuration.html#image-scrapers) from the sphinx gallery docs, together with the [custom image scrapers](https://sphinx-gallery.github.io/stable/advanced.html#custom-scraper) docs, suggests to me that grabbing the mpl scraper function will require messing with sphinx-gallery internals. So imma leave this be for now... 😅 

However, we should probably add the qtgallery scraper to the list in the sphinx-gallery docs! (Step 2 in [this comment](https://github.com/sphinx-gallery/sphinx-gallery/issues/441#issuecomment-493782430).)

**Comment by psobolewskiPhD** [comment]
Used by surface texture example.

**Pull request merged**
