### PR TITLE
Update URL of version switcher

### PR DESCRIPTION
**Pull request by melissawm**
# Description
Updates URL of version switcher to use https://napari.org/dev/_static/version_switcher.json

## Type of change

- [ ] Fixes or improves existing content
- [ ] Adds new content page(s)
- [x] Fixes or improves workflow, documentation build or deployment

# References
This is a follow-up on #109.

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Hmm, when I check index.html of the artifact, I now get the dev page and not stable:https://output.circle-artifacts.com/output/job/ce986846-a37c-4a4f-89d7-55fc2dc7aea2/artifacts/0/docs/_build/index.html

So I assume napari.org will just point to the dev version—we've talked about wanting to do that, but it means the API docs are also not the release version...

**Comment by melissawm** [comment]
Oh you are right, let me check this!

**Comment by melissawm** [comment]
OH I am sorry, my brain is not working so well today 😄 This is expected, since we are checking the artifacts on the PR (and PRs mean dev). I am pretty sure this will not cause the website to point to dev instead of stable.

**Comment by psobolewskiPhD** [comment]
I checked another PR and the CircleCI artifact also points to `latest` so false alarm. sorry!

**Review by jni — APPROVED** [review]

**Comment by jni** [comment]
Thank you @melissawm! And we also want to update it where it's already in use in napari.github.io, right? (ie in past versions of the docs?)

**Comment by melissawm** [comment]
Yup, will do that now!

**Pull request merged**
