### PR TITLE
Add a note about how blending interacts with canvas

### LINKED ISSUE #64: The docs describing blending modes need to explain interaction with themes
## 🧰 Task

Right now, the theme determines the canvas color: black (0, 0, 0) in dark mode, white (1, 1, 1) in light mode. This affects both additive and minimum blending.
The bottom-most visible layer with additive blending will blend with the canvas. Adding to (1, 1, 1) can't work, so white will be returned, so additive blending will appear to not work in Light mode.
The opposite is true for minimum blending: the minimum will always be 0, so minimum blending for the bottom-most layer won't work with a dark canvas.
Both of these issues can be worked around if there are 2+ layers and the bottom layer is set to translucent/opaque so it doesn't blend with the canvas. Or by changing theme or by overriding the canvas color using `viewer.window.qt_viewer.canvas.background_color_override`, but this is deprecated and also not available in the GUI at the moment, see: https://github.com/napari/napari/issues/5389

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
# Description
This PR adds an `Important` note to explain how blending modes (additive and minimum) interact with the UI theme. This is not intuitive, because the theme sets the canvas color and the bottom-most layer blends with the canvas: 
1. If you are using the default *Dark* theme, `minimum` blending for the bottom-most visible layer will result in all black ([0, 0, 0] of the canvas is the minimum).
2.  If you are using the *Light* theme, `additive` blending for the bottom-most visible
layer will  result in all white ([1, 1, 1] of the canvas is the maximum). 

## Type of change

- [x] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References
Fixes https://github.com/napari/docs/issues/64

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Comment by brisvag** [comment]
Didn't we have a bot that gave us a link to the build docs for each PR?

**Comment by psobolewskiPhD** [comment]
> Didn't we have a bot that gave us a link to the build docs for each PR?

We did on the other repo...
Here's the PR that made it less spammy:
https://github.com/napari/napari/pull/5148
But from some cursory looks, I don't see any PR comments with the docs link *after* that PR was merged—and it's not a split repo casualty, because there was a ~2 week period before the repos split.
Anyhow, while not as nice as the link to preview docs that numpy has, it was still convenient.

**Comment by brisvag** [comment]
Yes, I remember we had that spam-reducing PR, but indeed I haven't seen the non-spammy version either. @melissawm, do you know what might be the issue?

More on topic: It's just cause I don't know how the `important` note looks like, so I wanted to check :P

**Comment by psobolewskiPhD** [comment]
You can manually see the built docs by download from here:
https://github.com/napari/docs/actions/runs/3679483129
image

**Comment by brisvag** [comment]
Looks good :+1: I'm wondering though if we should rather hurry up and decouple the canvas from the theme as we said, instead of writing explanations around it xD

**Comment by psobolewskiPhD** [comment]
Probably. My thought is this would at least be live in the Dev docs, so maybe searchable? or could at least point people to it.

**Comment by DragaDoncila** [comment]
@psobolewskiPhD does this need to change after we merge [#5143](https://github.com/napari/napari/pull/5143) - which btw I think is ready.

**Comment by psobolewskiPhD** [comment]
> @psobolewskiPhD does this need to change after we merge [#5143](https://github.com/napari/napari/pull/5143) - which btw I think is ready.

No, not really. This PR documents a—in my opinion—non-intuitive interaction between blending modes and the theme (which determines canvas color, which is blended with).
That PR just makes it easier to switch themes *for a given viewer*, for example to work around this interaction.

**Comment by melissawm** [comment]
> Yes, I remember we had that spam-reducing PR, but indeed I haven't seen the non-spammy version either. @melissawm, do you know what might be the issue?

Yes, unfortunately it looks like this is not working - it's on my todo list to try a better solution 👍🏻

**Review by DragaDoncila — APPROVED** [review]
Looks great, thanks @psobolewskiPhD!

**Comment by psobolewskiPhD** [comment]
Just a heads up this PR will require reworking once https://github.com/napari/napari/pull/5487 is merged (soon?) because that one fixes most of these issues.

**Comment by psobolewskiPhD** [comment]
After reviewing https://github.com/napari/napari/pull/5487 and the resultant behavior, I don't think it needs such a user-centric documentation. The behavior is transparent to the user.
Closing.

**Pull request closed without merging**
