### PR TITLE
Add roadmap board link to Roadmaps page

### LINKED ISSUE #182: Link the project roadmap on napari.org
## 🧰 Task
Add a link to the global project roadmap:
https://github.com/orgs/napari/projects/24/views/2?pane=info
to napari.org roadmaps page:
https://napari.org/dev/roadmaps/index.html

### PR DESCRIPTION
**Pull request by melissawm**
# Description

Adds link to GitHub board containing the napari roadmap to Roadmap page.

EDIT: [Rendered page is here](https://output.circle-artifacts.com/output/job/31a35d46-3a9c-414e-ad63-7f7a8a988b93/artifacts/0/docs/_build/roadmaps/index.html)

## Type of change

- [x] Fixes or improves existing content
- [ ] Adds new content page(s)
- [ ] Fixes or improves workflow, documentation build or deployment

# References
Closes #182 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added [alt text](https://webaim.org/techniques/alttext/) to new images included in this PR

### CODE REVIEW

**Review by lucyleeow — APPROVED** [review]
Thanks!

**Comment by lucyleeow** [comment]
I wonder if we should mention the roadmap in the contributing guide too? 'You can see our planned work/general direction in our current roadmap...?'

**Comment by melissawm** [comment]
Good point, let me add that!

**Review by brisvag — APPROVED** [review]

**Comment by melissawm** [comment]
I know this can be redundant but I think it's useful to point to the roadmap in both pages where you may land if you are interested in contributing.

**Review by psobolewskiPhD — APPROVED** [review]

**Review by jni — APPROVED** [review]
Nicely done including the info pane! 😊👏

**Pull request merged**
