### PR TITLE
Port release notes from 0.4.18 main repo to docs

### PR DESCRIPTION
**Pull request by jni**
# Description

Ports release notes from main repo to docs repo. See napari/napari#6034

### CODE REVIEW

**Comment by jni** [comment]
This should not be merged until napari/napari#6034 is merged so we can incorporate any fixes from there.

**Comment by jni** [comment]
This should be ready to merge! 🥳 🚀

**Comment by melissawm** [comment]
Can you also make sure these release notes are added to the toc in [_toc.yml](https://github.com/napari/docs/blob/3143a5d38b2b166ef5b1fc7aa49b801b8963c713/docs/_toc.yml#L144)? Thanks!

**Comment by jni** [comment]
Ooops! Very nice catch @melissawm! 😅 Done! 😊

**Pull request merged**
