### PR TITLE
Replace references to 'edge' attributes with 'border' in Points docs

### PR DESCRIPTION
**Pull request by jamesyan-git**
Depends on https://github.com/napari/napari/pull/6402

Updating documentation to match with new nomenclature.

## TODO:
 Please see [this issue ](https://github.com/napari/napari/issues/6541)for a discussion regarding refactoring other layer types (shapes, vectors,..)

### CODE REVIEW

**Comment by jamesyan-git** [comment]
still need to fix more areas, such as:
- [ ] NAP-4?? should this be updated retroactively
- [x] docs/tutorials/annotation/annotate_points.md
- [ ] screenshots

**Comment by DragaDoncila** [comment]
@jamesyan-git I would say no need to update the NAP would be surprised if others disagree

**Comment by jamesyan-git** [comment]
There are pre rendered videos and images that have "edge color" visible.
[The video annotation tutorial ](https://napari.org/stable/tutorials/annotation/annotate_points.html)has 1 video and 1 screenshot
[The how-to use points layer](https://napari.org/stable/howtos/layers/points.html) has 2 videos
This will have to be re-recorded or a note should be made. 
What do you think @jni , @psobolewskiPhD

**Comment by brisvag** [comment]
added "Depends on https://github.com/napari/napari/pull/6402" (using the "depends on" wording trigger the CI dependency check!)

**Comment by psobolewskiPhD** [comment]
@jamesyan-git @DragaDoncila Gentle bump -- the napari PR has merged (not sure why I can't rerun the action here)
Re: the videos and images, I think anything in the core layer guides should definitely be updated. 
The mouse video? That could probably slide with just a small disclaimer, although the edge-color is changing...

**Comment by jamesyan-git** [comment]
@psobolewskiPhD We spoke about this at graph working group last time, and decided we'll re-record the videos. I'll be on it next week :)

**Comment by melissawm** [comment]
Hi all, the change in name is causing the points layer guide to fail right now (see https://napari.org/dev/howtos/layers/points.html#setting-edge-or-face-color-with-a-color-cycle). Would it be possible to merge this PR and update the videos in a follow-up PR? Thanks!

**Comment by DragaDoncila** [comment]
@melissawm yeah sounds good, let's fix the tutorial first. Do you think we need an admonition for the deprecated name in images/videos?

**Comment by melissawm** [comment]
Yes that would be ideal I think - maybe just one big admonition at the top of the document would be enough?

**Review by DragaDoncila — APPROVED** [review]
Looks good to me with the admonition. @psobolewskiPhD if you're happy with this I think you can merge when you wake up! Otherwise I'll merge first thing tomorrow

**Comment by DragaDoncila** [comment]
I'm going to merge this now as it'll hopefully fix the tutorial, but please open issues and tag if there was any remaining feedback :pray:

**Pull request merged**
